baseURL = "https://prsv.ch/"
languageCode = "en-us"
title = "Welcome"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "gruvbox_dark"
    userName = "admin"
    pcName = "prsv"
    workDir = "home"
    profile = "profile.txt"
    ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
    stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
    commandDelay = 50
    
    description = """
    Hello, I run one of the biggest family of Tor Relays.
    Responsible for over 1000MB/s of traffic.
    
    If there is any questions or complaints, 
    Please Contact Me:
    Email: admin@prsv.ch
    
    
    """








    [Params.Tree]
    use = true
    files = [
        ["Tor Relay Metrics", "https://relays.0x7c0.com/family/0189052E1CD8BD73B2AF6084C99619B8ED73DD55/"],
        ["Tor Relay Specifications", "works/post.md"],
        ["Fingerprints", ".well-known/tor-relay/rsa-fingerprint.txt"]
    ]
