baseURL = "https://prsv.ch/"
languageCode = "en-us"
title = "Welcome"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "gruvbox_dark"

    [Params.Tree]
    use = true
    files = [
        ["Tor Relays", "https://yui.cat/family/56F6103EA47A895E920394CBD31E68905D45CF4F/"],
        ["Python", "https://www.example.com/"],
        ["Go", "/works/go.md"],
        ["Hugo", "/works/hugo.md"]
    ]
